server:
  port: 8080

spring:
  application:
    name: newtest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&charcterEncoding=utf-8&useSSL=false
    username: root
    password: password

mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.edu.holypearl.users.domain.entity